language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf build-essential pkg-config cmake libicu-dev libcunit1 libcunit1-dev ragel curl libtool autotools-dev autoconf automake
before_script:
  - cd ../
  - curl -L https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/CUnit-2.1-3.tar.bz2/download > CUnit-2.1-3.tar.bz2
  - tar xjvf CUnit-2.1-3.tar.bz2
  - cd CUnit-2.1-3
  - libtoolize
  - autoheader
  - automake --add-missing 1>/dev/null 2>/dev/null | true
  - autoreconf
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ../
  - git clone https://github.com/ajwans/libtoml.git
  - cd libtoml
  - cmake -G "Unix Makefiles"
  - make
  - export LD_LIBRARY_PATH=~/libtoml:$LD_LIBRARY_PATH
  - echo $LD_LIBRARY_PATH
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-toml/.travis_build_config.rb build_config.rb
script:
  - make all test
